sudo: required
services:
  - docker

before_install:
  - docker build -t arrcher/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arrcher/react-test npm run test

after_success:
  - docker build -t arrcher/multi-client ./client
  - docker build -t arrcher/multi-nginx ./nginx
  - docker build -t arrcher/multi-server ./server
  - docker build -t arrcher/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arrcher/multi-client
  - docker push arrcher/multi-nginx
  - docker push arrcher/multi-server
  - docker push arrcher/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-168501346208"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY